### PR TITLE
Add extension field for common environment variables

### PR DESCRIPTION
**Pull request by DennisGaida**
I'm quite a fan of not repeating myself. I see you are using a few environment variables quite often such as `$PUID`, `$PGID` and `$TZ`.

I like using extension fields to get rid of these repetitions: https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields, or better explained here: https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd

I took the liberty of creating one extension field (I do have a couple more) for replacing these common environment variables:
```yaml
########################### EXTENSION FIELDS
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID
```
They can be used by just dropping this line `<< : *default-tz-puid-pgid` instead of an environment variable.

### CODE REVIEW

**Comment by htpcBeginner** [comment]
These are great additions! I will probably endup making just one minor change with the bash_aliases. I might use dip and dips instead. I am in the process of aligning/harmonizing my aliases and all docker commands start with just "d" instead of "doc". And all docker-compose commands start with "dc".

**Comment by htpcBeginner** [comment]
One question, do you see any opportunities to use anchors and aliases in this repo?

**Comment by DennisGaida** [comment]
When I found out about anchors and aliases I fell in love and yes, most definitely there can be many places we could make use of them in the humongous stack you have. I do use it for example for some default extra hosts such as for authelia (also take note of my variable name for the INTERNAL/EXTERNAL domain - I really didn't like your DOMAIN0 DOMAIN1 nomenclature):
```
x-extra_hosts: &default-extra_hosts
  - "${AUTHELIA_SUBDOMAIN_INTERNAL}.${DOMAIN_INTERNAL}:host-gateway"
```

Besides that I feel that anchors/aliases also hurt readability if used too much. We could have it as well for the network stacks for example - the "traefik" stack, the "traefik + socket proxy stack" and so on - but I believe that wouldn't help with readability.

**Comment by htpcBeginner** [comment]
Let me know what you think: https://github.com/htpcBeginner/docker-traefik/commit/79d035b08de5f3389458226cf634b149e264981b

**Comment by DennisGaida** [comment]
Love them. Stealing them 🥷

**Pull request merged**
